name: Elixir CI

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [24.0.1]
        elixir: [1.12.1]

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pipsqueak_test
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - run: openssl version
      - run: sudo apt-get install open-ssl
      - run: sudo apt update
      - run: sudo apt upgrade
      - run: sudo apt install wget build-essential checkinstall zlib1g-dev
      - run: sudo cp -R /usr/lib/ssl /usr/lib/ssl-1.1.1h
      - run: wget https://www.openssl.org/source/openssl-1.1.1h.tar.gz
      - run: wget https://www.openssl.org/source/openssl-1.1.1h.tar.gz.sha256
      - run: tar -zxf openssl-1.1.1h.tar.gz
      - run: cd openssl-1.1.1h
      - run: ./config
      - run: make
      - run: make test
      - run: sudo make install
      - run: sudo mv /usr/bin/openssl /usr/bin/openssl-1.1.1f
      - run: sudo ln -s /usr/local/bin/openssl /usr/bin/openssl
      - run: sudo ldconfig
      - run: openssl version
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.4

      - uses: actions/cache@v1
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - uses: actions/cache@v1
        id: build-cache
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install deps
        run: |
          mix deps.get
          (cd assets && yarn)

      - run: mix dialyzer
      - run: mix credo
      - run: mix format --check-formatted
      - run: mix test
  
  deploy:
    # only run this job if the verify job succeeds
    needs: verify

    # only run this job if the workflow is running on the master branch
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
        # actions/checkout@v2 only checks out the latest commit,
        # so we need to tell it to check out the entire master branch
        with:
          ref: master
          fetch-depth: 0

      # configure the gigalixir-actions with our credentials and app name
      - uses: mhanberg/gigalixir-action@v0.1.0
        with:
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          GIGALIXIR_APP: nfl
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
